### PR TITLE
Linux Encode: Only sync on CPU when neccessary

### PR DESCRIPTION
**Pull request by nowrep**

### CODE REVIEW

**Comment by nowrep** [comment]
@andy-d1969 Can you please test this with AMF?

**Comment by andy-d1969** [comment]
No issues here.

**Comment by Vixea** [comment]
I'll probably test it around 10 working extra late today.

**Comment by Vixea** [comment]
Tested on VAAPI works fine, I'm assuming you've done software?

**Comment by nowrep** [comment]
Yes, I tested with all encoders except AMF and NVENC (but nothing to test here).

**Comment by Vixea** [comment]
ok merging

**Pull request merged**
