### PR TITLE
Add missing nls

### PR DESCRIPTION
**Pull request by sctanf**

### CODE REVIEW

**Comment by ckiee** [comment]
What about the [graph hover popup](https://i.ckie.dev/eB1SjDG.png)? I don't think this covers that.

**Comment by sctanf** [comment]
> What about the [graph hover popup](https://i.ckie.dev/eB1SjDG.png)? I don't think this covers that.

Thanks for pointing that out
I made some commits, can you test it?

**Comment by ckiee** [comment]
This might just be falling back because of this specific localization but [there's still some missing](https://i.ckie.dev/Wv1S47d.png).

**Comment by sctanf** [comment]
It's fallback, since most are new entries

**Comment by ckiee** [comment]
@sctanf Okay to merge this as `Add missing i18n translations (#801)` for the commit message?

**Pull request merged**
