### PR TITLE
Update prepare-release.yml to pull nv-codec-headers

### PR DESCRIPTION
**Pull request by Killrmemz**
Fixes NVEnc for Linux users, and not just the people using AUR.

### CODE REVIEW

**Comment by zarik5** [comment]
LGTM

**Comment by zarik5** [comment]
You need to make a similar PR to the nightly repo

**Comment by MadByteDE** [comment]
Just want to say thanks for the patch @Killrmemz. It finally works for me OOTB with the latest nightly release (AppImage).

**Comment by zarik5** [comment]
Ready for a release then :)

**Comment by guysoft** [comment]
Oh great! Will test that since it was broken for me after upgrading to Ububtu 24.04

**Pull request merged**
