### PR TITLE
Linux: Specify rate control params for software encoding

### PR DESCRIPTION
**Pull request by deiteris**

### CODE REVIEW

**Review by nowrep — APPROVED** [review]
LGTM now

**Comment by deiteris** [comment]
Wait, why divide by 10? The buffer is going to be huge at some point. What is wrong with 1 frame buffer size?

**Comment by nowrep** [comment]
> What is wrong with 1 frame buffer size?

It degrades image quality a lot with sw encoder (x264).

**Comment by deiteris** [comment]
I think better logic would be to use `encoder_ctx->bit_rate / settings.m_refreshRate * n`, where `n` is number of buffered frames and find the number that it ok, just to make it consistent. For our case, it normally should be 1.1 frame (and maybe for all other encoders too actually).

**Comment by nowrep** [comment]
`encoder_ctx->bit_rate / settings.m_refreshRate * 1.1` actually does work, but the result is exactly the same as bit_rate/10 or leaving it at the default value.
In any case, "improving" sw encode is pointless until it works without forcing all idr anyway. openh264 works fine with p-frames but also the encoder is very slow.

**Comment by deiteris** [comment]
Well, it's not only about improving sw encoding, but also other encoders should have this value set properly :) It can be better in terms of quality, but is it the same in terms of latency?

**Comment by nowrep** [comment]
The latency and image quality is exactly the same for *any* value >= `encoder_ctx->bit_rate / settings.m_refreshRate * 1.1`

**Comment by deiteris** [comment]
I'll try experimenting on Windows with different setups. I think that's the value that we might want to use for all encoders (and maybe min_bitrate is actually useless in that case).

**Pull request merged**
