### PR TITLE
[Working] Green Screen Chroma Key Passthrough - Enable OpenXR

### PR DESCRIPTION
**Pull request by beiller**
I attempted to add green screen pass-through, and got stuck trying to get the pass-through to be "over top" the "video stream". If I move my head real fast I can see the pass-through in the lags that the video is not covering so I think it's progress.

### CODE REVIEW

**Comment by beiller** [comment]
If anyone is able to help me make the passthrough appear over the video stream, even just setting alpha to zero doesn't seem to work. I tried changing all the GLSL shaders to set .a = 0.0 to no avail. Tried various GL clear flags etc.

Once that works I can write code to toggle it as well as chroma key GLSL code. I just can't seem to make it pass through however.

**Comment by zarik5** [comment]
I believe you will have to set the alpha channel == 0 for every shader in the compositor. The reason I haven't implemented passthrough yet is because I wanted to rewrite the client compositor since the current OpenGL one is pretty messy.

**Comment by Vixea** [comment]
It's best to use an epsilon when comparing floats btw or alpha < 0.01. If I understand what you're trying to do here zarik

**Comment by beiller** [comment]
@zarik5 I tried that all the glsl I could find and set `.a = 0.0` for all of them and it didn't pass through. I just reverted that change since it didn't seem to work. Only on the outside of the frame I could see slivers of pass-through. Or maybe can you point me to a particular shader of interest?

**Comment by zarik5** [comment]
@beiller There are a few shaders: gamma correction, FFR, and one last one to split the image between the two eyes. To be honest the code is very old and quite bad, I can't help you much further unless I dig into that more.

**Comment by beiller** [comment]
Thanks for your comments @zarik5 I will try it out. I will think on it some more because I feel there is something higher level than GLSL that is setting the alpha blending.

**Comment by zarik5** [comment]
It's useful to disable/bypass some code temporarily, for debug purposes. for example in the shader to render to the final swapchains, discard the texture values and always set (0, 0, 0, 0).

**Comment by zarik5** [comment]
@beiller, instead of writing raw ffi code in ALVR itslef, are you able to add the passthrough bindings to our [openxrs fork](https://github.com/alvr-org/openxrs)?

**Comment by beiller** [comment]
Hey @zarik5 the good news is I don't need all that I guess I was just using it to debug. I have a new working implementation obviously missing a lot and is hard-coded to chromakey green currently. Maybe we can turn it into a feature somehow.

**Comment by beiller** [comment]
Need way to toggle and maybe some small cleanup before this could ever be considered. 
 - Need to toggle feature on/off with key combo
 - Need to remove required: true for passthrough component in open XR
 - Need to test on more devices (I have quest2 only)

**Comment by Meister1593** [comment]
Does not seem to work on pico 4 (pro, 5.9.1 pui)?... Just black screen
Screenshot_alvr client_2024 02 21-12 24 35 418_640

**Comment by Vixea** [comment]
> Does not seem to work on pico 4 (pro, 5.9.1 pui)?... Just black screen Screenshot_alvr client_2024 02 21-12 24 35 418_640

check for shader compile error in logcat

**Comment by Meister1593** [comment]
> > Does not seem to work on pico 4 (pro, 5.9.1 pui)?... Just black screen Screenshot_alvr client_2024 02 21-12 24 35 418_640
> 
> check for shader compile error in logcat

Any specifics for compiler error message? Don't seem to find much of anything with "shader" in logs

**Comment by Vixea** [comment]
nah not really just search for err or error

**Comment by Meister1593** [comment]
From what i can tell, it compiled shaders just fine and runtime recognized passthrough
```
02-21 13:04:11.107 30004 30032 I [ALVR Native]: Compiling shaders.
02-21 13:04:11.108 30004 30032 I [ALVR Native]: Successfully compiled shader.
02-21 13:04:11.108 30004 30032 I [ALVR Native]: Compiling shaders.
02-21 13:04:11.108 30004 30032 I [ALVR Native]: Successfully compiled shader.
02-21 13:04:11.109 30004 30032 E APxrRuntime:  oxr_session_poll:XRT_COMPOSITOR_EVENT_SEETHROUGH_CHANGE-------:0
```

**Comment by Meister1593** [comment]
fb_passthrough is available and being used

**Comment by beiller** [comment]
Ah so it is just black where the passthrough should be seen? That is at least "working". If the shader has issue the app just crashes :)

I did hack around with it until it works so I think there may be something missing in the code. I can try experimenting with some things if you can help test pico 4.

**Comment by Meister1593** [comment]
> Ah so it is just black where the passthrough should be seen? That is at least "working". If the shader has issue the app just crashes :)
> 
> I did hack around with it until it works so I think there may be something missing in the code. I can try experimenting with some things if you can help test pico 4.

Sure thing, i can test it of course

**Comment by beiller** [comment]
OK maybe it is caused by `"com.oculus.feature.PASSTHROUGH"` Is there some other feature that needs to be enabled for Pico do we think?

**Comment by beiller** [comment]
@Meister1593 I found maybe an issue, the features aren't properly returned. Can you try compiling with this commit and let me know? I think I may have had a different build on my device. With the "if" statements uncommented I got similar black screen behavior that you see.

**Comment by Meister1593** [comment]
> @Meister1593 I found maybe an issue, the features aren't properly returned. Can you try compiling with this commit and let me know? I think I may have had a different build on my device. With the "if" statements uncommented I got similar black screen behavior that you see.

just tried, nothing changed, exactly the same thing
Checked one of the passthrough apps (it's unity though) and android props, tried to copy them - nothing changed
```
[[package.metadata.android.application.meta_data]]
name = "MRCsupport"
value = "1"
[[package.metadata.android.application.meta_data]]
name = "color_Space"
value = "1"
[[package.metadata.android.application.meta_data]]
name = "rendering_mode"
value = "0"
```

**Comment by Meister1593** [comment]
From brief discussion in the server i've changed layer mode from OPAQUE to ALPHA_BLEND and it started to work.
I will try to work on providing settings from server to client to make chromakey colour, range and toggle be adjustable.

**Comment by JackD83** [comment]
I just tried this PR with the latest master. Works great, but I had to manually merge graphics.cpp.  I just have a major flaw: If the application running in SteamVR is dropping frames (e.g late start frames), the frame gets cleared to paththrough and  the rendered content starts to flicker. 
I don't know enough about the inner workings and shader in general to fix this. Is there even a chance to solve this?

**Comment by JackD83** [comment]
Sorry for not reporting back. The issue was not caused by the passtrough but a bug in ALVR itself. The bug is already fixed: https://github.com/alvr-org/ALVR/commit/d42701bb82eec7457b6023252f8068c2917197ee

Late start frames are not causes by slow rendering but by a slow cpu. In our case the generation of textures in the unity main thread that takes too long.

**Comment by beiller** [comment]
I will close now as the code has moved on. I have an updated PR here

https://github.com/alvr-org/ALVR/pull/2551

**Comment by beiller** [comment]
I will close as the code has moved on and I opened a new PR here:
https://github.com/alvr-org/ALVR/pull/2551

**Pull request closed without merging**
