### PR TITLE
Fix SteamVR recentering on Linux

### LINKED ISSUE #1246: Using in-app recenter buttons causes flickering and white flashes
## Description
Using in-app recenter buttons causes lots of flickering and white flashes. Pressing oculus's recenter button ends the problem, but sets a wrong position.  (Seems to happen everywhere, tested on Yiffalicious and VR Paradise)

So, when you open a game you're in the wrong place, however if you use the recenter button it starts flickering a lot (on every single slight head movement (even breathing)) together with white lines that flash (lines are round and directed to the screen's edge).

## General Troubleshooting
- [ y] I carefully followed the instructions in the [README](https://github.com/alvr-org/ALVR/blob/master/README.md) and successfully completed the setup wizard
- [y ] I read the ALVR Wikis [here](https://github.com/polygraphene/ALVR/wiki) and [here](https://github.com/alvr-org/ALVR/wiki)

### Hardware
**Note**: for Linux, an upload to the [`hw-probe`](https://linux-hardware.org/) database is preferred: `hw-probe -all -upload`

Here, but it's wrong. It detected KDE, but I use XFCE (even tho KDE and gnome are instaled, I do not use them): https://linux-hardware.org/?probe=4e0b0368b8

Here's a Neofetch with correct info:
luana@Luana-Z370XP-SLI 
---------------------- 
OS: openSUSE Tumbleweed x86_64 
Host: Z370XP SLI 
Kernel: 6.0.7-1-default 
Packages: 6290 (rpm), 37 (flatpak), 15 (snap) 
Shell: zsh 5.9 
Resolution: 1920x1080 
DE: Xfce 4.16 
WM: compiz 
Terminal: xfce4-terminal 
CPU: Intel i7-8700K (12) @ 4.700GHz 
GPU: NVIDIA GeForce GTX 1070 Ti 
Memory: 3541MiB / 32039MiB 

**Audio**: pipewire / jack

### Installation
**ALVR Version**: v19.0.0-dev02+nightly.2022.09.19 (cannot update because of #1248)

**SteamVR Version**: 1.24.6

**Install Type**:
[] Packaged (`exe`, `deb`, `rpm`, etc)
[y ] Portable (`zip`)
[] Source

**OS Name and Version** (`winver` on Windows or `grep PRETTY_NAME /etc/os-release` on most Linux distributions): OpenSUSE Tumbleweed

### PR DESCRIPTION
**Pull request by nowrep**
Closes #1246

### CODE REVIEW

**Comment by LuNeder** [comment]
👀 Nice

**Comment by zarik5** [comment]
@LuNeder does this PR fix your issue? is everything else working as expected?

**Comment by LuNeder** [comment]
> @LuNeder does this PR fix your issue? is everything else working as expected?

If this pr is already present in latest nightly, it unfortunately does not

See (screen recording included): https://github.com/alvr-org/ALVR/issues/1246#issuecomment-1467230583

**Comment by nowrep** [comment]
This fixes the recentering from SteamVR overlay which modifies `RawZeroPoseToStandingAbsoluteTrackingPose`.
If recentering in a game works differently, this won't fix it of course.

**Comment by LuNeder** [comment]
A workaround that worked for me was using the SteamVR recenter button instead of the in-app one: this puts you in the correct place and doesn’t gets buggy
Em 14 de mar. de 2023 11:21 -0300, galister ***@***.***> escreveu:

**Comment by LuNeder** [comment]
> A workaround that worked for me was using the SteamVR recenter button instead of the in-app one: this puts you in the correct place and doesn’t gets buggy

Nevermind, I guess I was just lucky that day. Disabling rotation recenter doesn’t help either.

**Pull request merged**
