### PR TITLE
fix(launcher): :bug: Fix installation popup

### PR DESCRIPTION
**Pull request by zarik5**

### CODE REVIEW

**Comment by The-personified-devil** [comment]
How does this work?

**Comment by KyleCarr** [comment]
This change makes it so instead of creating a copy of the release channel version, it is actually mutable. This should save memory overall I believe right?

**Comment by zarik5** [comment]
Basically i refactored away some logic for the popup, and in doing so we now need to call some code in a closure. Closures often means aliasing issues so I usually clone the variables needed. This time though we needed to mutate the variable (`version`) so the result was that the dropdowns didn't select anything anymore.

**Comment by The-personified-devil** [comment]
> This change makes it so instead of creating a copy of the release channel version, it is actually mutable. This should save memory overall I believe right?

Yea that's what the diff says, but the question is why it's done. It's clearly a fix going by the diff message, so this somehow has to fix something

**Review by The-personified-devil — APPROVED** [review]

**Comment by zarik5** [comment]
@KyleCarr this is not about memory saving. It was actually a bug caused by a refactoring. Most of the code in ALVR doesn't care about memory usage, apart some crucial paths while dealing with video buffers

**Review by KyleCarr — APPROVED** [review]

**Comment by zarik5** [comment]
Yeah I would have never found this myself even staring at the code for hours. It was reported in the Discord server. It slipped my testing apparently.

**Comment by The-personified-devil** [comment]
> Yeah I would have never found this myself even staring at the code for hours. It was reported in the Discord server. It slipped my testing apparently.

Well yea, finding the initial bug, but finding the reason for the change is reasonably doable I think

**Pull request merged**
