### PR TITLE
fix request game audio list error

### PR DESCRIPTION
**Pull request by happychui**

### CODE REVIEW

**Comment by Vixea** [comment]
How did you reproduce this error?

**Comment by zarik5** [comment]
@happychui Can you provide more feedback? This PR does seem to break audio list report when the dashboard is opened after the server.

**Comment by zarik5** [comment]
@happychui Thanks for the report. I've decided to fix this on the server side and I already pushed the fix on the master branch. Please tell me if this fixes it for you.

@Vixea The error could be reproduced if the driver was manually registered, then launched SteamVR first, then the dashboard.

**Comment by happychui** [comment]
I'm glad to help you.

**Pull request closed without merging**
