### PR TITLE
Fix blur with foveated encoding (option 2)

### PR DESCRIPTION
**Pull request by deiteris**

### CODE REVIEW

**Comment by zarik5** [comment]
@deiteris Can you also format the FFR shader code a bit better while you are at it?

**Comment by deiteris** [comment]
I've updated the formatting. Is this what was required? I'm not sure how to format `leftEdge` and `rightEdge`...

**Comment by zarik5** [comment]
I'm not sure either. The spacing is good, can you also break that into multiple lines? just following the brackets.

**Comment by deiteris** [comment]
I guess we could just leave this to C++ formatter. These expressions are hard to comprehend, let alone formatting. Updated the formatting.

**Comment by galister** [comment]
tested and looks good!

**Comment by galister** [comment]
also much better on performance than doing full res srgb pass -> ffr pass. about on par with the single-pass one

**Comment by deiteris** [comment]
I haven't compared the single-pass to two-pass, but this PR does improve GPU and frame time:

Before:
image

After:
image

**Review by zarik5 — APPROVED** [review]
Looks good! I think it's ready to merge. The CI failure is unrelated.

**Comment by galister** [comment]
still tests ok as of [4a97bcd](https://github.com/alvr-org/ALVR/pull/1434/commits/4a97bcd290a91b895a1b82d868441415060fe15e)

**Comment by zarik5** [comment]
Great, merging.

**Pull request merged**
