### PR TITLE
NvEnc: Set gop_size to INT16_MAX

### PR DESCRIPTION
**Pull request by nowrep**

### CODE REVIEW

**Comment by Vixea** [comment]
Thanks

**Comment by zarik5** [comment]
There seems not be no testers for Linux/Nvidia, I'll merge anyways.

**Comment by Vixea** [comment]
> There seems not be no testers for Linux/Nvidia, I'll merge anyways.

double negative :P

**Comment by zarik5** [comment]
damn it, I just woke up

**Comment by Vixea** [comment]
good news is I brought my old nvidia gpu back up with me so all what I need is to being up the rest of the parts and well buy a cpu not looking forward to that part tho :P

**Pull request merged**
