### PR TITLE
Linux: Distrobox ALVR packaging implementation

### PR DESCRIPTION
**Pull request by Meister1593**
This PR prepares new packaging method for ALVR in the form of using containers through distrobox.

It was chosen because it is designed to be as close to desktop as possible, flexible enough for installing vr or any other software on top of it and was fairly well maintained and supported for such use case.

This method of installing alvr should make it much easier to have pretty much the same environment across the distributions, and make using alvr, steamvr a lot less painful on linux.

### CODE REVIEW

**Comment by Vixea** [comment]
I'd prefer if audio related stuff came in its own folder as it is useful outside of distrobox and same with patching SteamVR

**Comment by Meister1593** [comment]
> I'd prefer if audio related stuff came in its own folder as it is useful outside of distrobox and same with patching SteamVR

they are both in gist format there
https://gist.github.com/Meister1593/b574b399d85770abc2368f4d5af9df42
https://gist.github.com/Meister1593/c211099de9c82cfa2d35711fc8a28cb3
but they might quickly get obsolete, and second one is already needs updating, so i might move it into separate folder yeah

**Comment by Vixea** [comment]
Any quick comments from anyone?

**Comment by Meister1593** [comment]
I still haven't separated scripts from the directory, but in general script looks very promising, currently ongoing testing with linux mint nvidia user

**Pull request closed without merging**
