### PR TITLE
fix(client_core): :bug: Fix staging texture resolution

### LINKED ISSUE #2374: Horizontal resolution halved by staging texture
view_resolution is a per eye resolution while staging_texture contains both eyes so its width should be doubled
https://github.com/alvr-org/ALVR/blob/b71059f18b49c2d8d512e75267eaed61cfae6ce1/alvr/client_core/src/graphics/stream.rs#L80
https://github.com/alvr-org/ALVR/blob/b71059f18b49c2d8d512e75267eaed61cfae6ce1/alvr/client_core/src/graphics/stream.rs#L206

### PR DESCRIPTION
**Pull request by zarik5**
Fixes #2374

### CODE REVIEW

**Review by The-personified-devil — APPROVED** [review]

**Comment by ShootingKing-AM** [comment]
Can you explain more about this, what was happening before and whats the fix about ? Its effect on decoder latency  ? I think this will increase the latency even more

**Comment by zarik5** [comment]
@ShootingKing-AM This has nothing to do with latency. it's simply a bug where the decoder output has a certain size but we render it to a texture with half the width. OpenGL itself doesn't care about these bugs.

**Comment by The-personified-devil** [comment]
Fixes #2374

**Comment by zarik5** [comment]
@The-personified-devil it did

**Comment by The-personified-devil** [comment]
@zarik5 it did cause I edited your message to do it

**Comment by zarik5** [comment]
gotcha

**Pull request merged**
