### PR TITLE
Pico: restore squeeze and trigger click actions

### PR DESCRIPTION
**Pull request by galister**
apparently the pico needs these, too.

### CODE REVIEW

**Comment by zarik5** [comment]
These actions are not supported by the Focus 3. If you want you can add them for Pico in the if block.

**Comment by galister** [comment]
> These actions are not supported by the Focus 3. If you want you can add them for Pico in the if block.

Done.

**Comment by galister** [comment]
fixed conflict.

**Comment by zarik5** [comment]
nice!

**Pull request merged**
