### PR TITLE
Server: Limit bitrate by default 

### PR DESCRIPTION
**Pull request by Vixea**
Fixes the bit-rate to a range lower than 100 mbs to keep the XR2's decoder happy 🥳 
Needs testing to make sure latency doesn't balloon in any case(all encoders that can do HEVC).

### CODE REVIEW

**Comment by zarik5** [comment]
Since we don't know the clear reason and circumstances where the decoder would run late, I would do something different, that is setting the max bitrate limit at 100 and on by default.

**Comment by Vixea** [comment]
Can you describe what you would do differently?

**Comment by Vixea** [comment]
Since this is getting squashed the little extra commits are fine, right?

**Review by zarik5 — APPROVED** [review]

**Comment by zarik5** [comment]
Sure

**Comment by Kirottu** [comment]
HEVC at 300MBPS on 100% resolution works perfectly fine for me, only at higher refresh rates and higher resolutions it starts getting out of hand.

**Comment by Vixea** [comment]
Good to know but these should be for the lowest denominator which starts having issues at above 100

**Comment by Vixea** [comment]
If your suggesting I change it that is

**Comment by Kirottu** [comment]
What I'm saying is that it is likely that limiting the bitrate to 100MBPS wouldn't actually help, as I'm pretty sure the latency runaway would happen with 100MBPS too given high enough refresh rate and resolution.

**Comment by Vixea** [comment]
Good news is I doubt the XR2 would be happy with that resolution anyway

**Comment by Vixea** [comment]
Is this still needed after  "AdaptiveWithLatency option; add max latency"

**Comment by zarik5** [comment]
I think this should be investigated more. Do some tests with different refreshrates, resolutions and bitrates, and extrapolate a general trend. Then we can decide what to do.

**Comment by Vixea** [comment]
closing do to recent changes in master

**Pull request closed without merging**
