### PR TITLE
dashboard(linux): add old audio script check

### PR DESCRIPTION
**Pull request by Meister1593**
Probably should have been added with pipewire impl at the same time, but if user doesn't reset it - most likely user will think audio is broken or misbehaving.

image

### CODE REVIEW

**Comment by zarik5** [comment]
Uh sure. The user is supposed to reset the settings anyway. But i know how it is. That's why i keep checking for handshake packets of all previous ALVR versions so i can show an error that says to upgrade.

**Review by zarik5 — COMMENTED** [review]
I think this is overkill. Why don't implement this as a setup wizard page? if you want you can make dynamic/conditional controls also on setup pages.

**Comment by Meister1593** [comment]
> Uh sure. The user is supposed to reset the settings anyway. But i know how it is. That's why i keep checking for handshake packets of all previous ALVR versions so i can show an error that says to upgrade.

No one does this unfortunately, and it's very bad to recommend someone to reset all settings, it's very inconvenient for users.

> I think this is overkill. Why don't implement this as a setup wizard page? if you want you can make dynamic/conditional controls also on setup pages.
Doesn't setup page never gets shown after you initially remove it? I implemented it in this way because if it got disabled, this never gets shown. Also this is conditional window, that will never get shown for new users.

**Comment by Meister1593** [comment]
Technically i can move it to setup wizard, but only if each update setup wizard shows for everyone, not just for new users.

**Comment by Meister1593** [comment]
We really should think about settings migration and keeping default (in current version) and custom values stored in schema

**Comment by Meister1593** [comment]
Hm, i may have not noticed that setup wizard always shows on version change, gonna do it in setup wizard then

**Comment by Meister1593** [comment]
One more note, we can't have conditional page right now, it needs to be implemented not through match/enums

**Comment by zarik5** [comment]
> No one does this unfortunately, and it's very bad to recommend someone to reset all settings, it's very inconvenient for users.

Still, this is solves errors for a good chunk of people after upgrading.

**Comment by zarik5** [comment]
Maybe you think we should need a list of settings that should be reset for each new version? I'm not sure i want to maintain that

**Comment by Meister1593** [comment]
> > No one does this unfortunately, and it's very bad to recommend someone to reset all settings, it's very inconvenient for users.
> 
> Still, this is solves errors for a good chunk of people after upgrading.

Maybe, but no one would like that for sure, and i myself don't like that too, it's not good to force user to re-do configuration, especially considering releases can happen multiple times per month.

> Maybe you think we should need a list of settings that should be reset for each new version? I'm not sure i want to maintain that

We need to think first about just adding default + custom value definition to schema, otherwise we don't know if it's changed even for current version, then later we can think about creating proper schema migration (instead of just reverting it to default)

**Comment by zarik5** [comment]
> We need to think first about just adding default + current value definition to schema, otherwise we don't know if it's changed even for current version, then later we can think about creating proper schema migration (instead of just reverting it to default)

I'm not sure you understand. schema by definition should not contain custom value. And we do have some automatic session migration, per setting, but it's still quite lossy. We definitely cannot predict the intention of the user. And trying to add more info for the meaning for each setting is going to be pure nightmare, largely unnecessary. Instead one good thing to add is search for the same setting if it has been moved in a different section.

**Comment by Meister1593** [comment]
> I'm not sure you understand. schema by definition should not contain custom value. And we do have some automatic session migration, per setting, but it's still quite lossy. We definitely cannot predict the intention of the user. And trying to add more info for the meaning for each setting is going to be pure nightmare, largely unnecessary. Instead one good thing to add is search for the same setting if it has been moved in a different section.

Understood, though to keep it within MR i will probably add to reset settings button and very visible note about script being present (as you noted)

Every user anyway goes through setup wizard at least up until to second page and obvious sign with big text about script should be enough

**Review by Vixea — CHANGES_REQUESTED** [review]
Hasn't moved to setup wizard

**Comment by Meister1593** [comment]
At this point, i think i would rather re-do the PR and post it fresh if it's even required, i didn't see much of anyone lately having problems with this anyway.

**Pull request closed without merging**
