### PR TITLE
Select codec type lazily

### PR DESCRIPTION
**Pull request by zarik5**
This is a stub to support dynamically selected encoder.

### CODE REVIEW

**Comment by nowrep** [comment]
I think this should work.

```diff
diff --git a/alvr/server/cpp/platform/linux/EncodePipelineSW.cpp b/alvr/server/cpp/platform/linux/EncodePipelineSW.cpp
index ea13827b..149fe849 100644
--- a/alvr/server/cpp/platform/linux/EncodePipelineSW.cpp
+++ b/alvr/server/cpp/platform/linux/EncodePipelineSW.cpp
@@ -35,14 +35,9 @@ void x264_log(void *, int level, const char *fmt, va_list args)
 
 alvr::EncodePipelineSW::EncodePipelineSW(Renderer *render, uint32_t width, uint32_t height)
 {
+  Settings::Instance().m_codec = ALVR_CODEC_H264;
   const auto& settings = Settings::Instance();
 
-  if (settings.m_codec == ALVR_CODEC_H265)
-  {
-    // TODO: Make it work?
-    throw std::runtime_error("HEVC is not supported by SW encoder");
-  }
-
   x264_param_default_preset(&param, "ultrafast", "zerolatency");
   x264_param_apply_profile(&param, "high");
 
```

**Comment by zarik5** [comment]
Hmm, are you able to pass the codec parameter along? I don't like modifying settings themselves, they are supposed to be immutable.

**Comment by nowrep** [comment]
Sure, that was quick&dirty solution since it only applies to software encoder anyway.
`ParseFrameNals` can take codec parameter.

**Comment by zarik5** [comment]
Can I merge this PR as is and you take it from here in another PR?

**Comment by nowrep** [comment]
Yes

**Pull request merged**
