### PR TITLE
feat: send full view config to openvr

### PR DESCRIPTION
**Pull request by muxiaozi**

### CODE REVIEW

**Comment by Vixea** [comment]
This pr is lacking an explanation on why this should be necessary? Or what's it for

**Comment by muxiaozi** [comment]
Some VR devices have left and right glasses with rotation angles, and the current program assumes that they are parallel, which may cause rendering errors on those devices
image

**Comment by Vixea** [comment]
Ah, yea I forgot about that.

**Comment by zarik5** [comment]
@muxiaozi if it's ok with you I would like to work on this myself. This is going to be part of a tracking rewrite. I will reference your code and add you as coauthor.

**Comment by muxiaozi** [comment]
@zarik5  Of course, thank you

**Pull request closed without merging**
