### PR TITLE
io::ErrorKind::Interrupted error occurs on socket peek

### PR DESCRIPTION
**Pull request by happychui**
io::ErrorKind::Interrupted error occurs on socket peek

### CODE REVIEW

**Comment by The-personified-devil** [comment]
Just run `cargo xtask format` for the formatting. But what exactly is the reason you think this change should be made? Does it fix any particular issues?

**Comment by zarik5** [comment]
@happychui Are you in Windows or Linux? Does this happen on handshake or during streaming? Have you tested it thoroughly? There is no guarantee that the stream is valid after receiving that event, if using TCP.

**Comment by happychui** [comment]
Encountered on pico3 and pico4 devices。This problem occurs just a few data after connecting. It's a chance not a certainty that it will happen.
cd41f680bfd03f2b605ce9e1aeece2f

**Comment by happychui** [comment]
Using the tcp protocol

**Comment by zarik5** [comment]
It seems that the disconnection is caused by a client crash, not by the network code

**Comment by zarik5** [comment]
Try to tweak the code providing swapchain formats. It's in alvr/client_core/src/graphics/mod.rs

**Comment by happychui** [comment]
> It seems that the disconnection is caused by a client crash, not by the network code

client no crash, Ignoring this error the program can continue

**Comment by zarik5** [comment]
I'm closing this PR because the changes are not related to the issue

**Pull request closed without merging**
