### PR TITLE
reorganise flatpak stuff - and update wiki

### PR DESCRIPTION
**Pull request by failboat78**
add flatpak build environment back in different folder

### CODE REVIEW

**Comment by Meister1593** [comment]
do we really *need* to keep both?...

**Comment by failboat78** [comment]
> do we really _need_ to keep both?...

I am using it to do my test builds... Arch has problem with nvcc and gcc - I prefer to use containerised builds.

**Comment by The-personified-devil** [comment]
Flatpak is a pretty bad option for development. Which is fair considering its mainly intended for distribution anyway. The way better option for dependency issues when developing is nix anyway. Its ridiculously easy to just add nvcc to your build environment with it. We could think about shipping additional support for developing with nix, but thats a different issue.

**Comment by The-personified-devil** [comment]
In your case this should be enough to have a shell with a working nvcc: `nix-shell -p cudaPackages.cuda_nvcc`
Tho I'm not sure whether some other cuda stuff in alvr might not cause issues regardless. I guess I'll try it out when I can

**Comment by failboat78** [comment]
> In your case this should be enough to have a shell with a working nvcc: `nix-shell -p cudaPackages.cuda_nvcc` Tho I'm not sure whether some other cuda stuff in alvr might not cause issues regardless. I guess I'll try it out when I can

There is no impact - it's a seperate flatpak for developers only. It is not related to the launcher flatpak that users run. 

Someone else created this originally, it was there when I came along. All I did was add cuda to it so nvidia build would work.

**Comment by The-personified-devil** [comment]
> There is no impact - it's a seperate flatpak for developers only. It is not related to the launcher flatpak that users run.

It's a tool for developers and codebase bloat has an impact for developers too. Plus I think the nix solution solves this exact problem way more elegantly (way less complex, easier to use, takes up less storage).

> I don't know - but it's already in the repo. 

It was in the repo, it got removed and I think removing it is the right choice and it should be kept that way.

> Building and development are not the same thing. Having a flatpak build does not change anyones development workflow.

Building is a part of development. Regardless, I think a solution to improve the issues with cuda on linux for building alvr should have an impact on build workflow for everyone that wants to build with nvidia by making it way easier for them. And in my personal experience flatpak does not fulfill that.

**Pull request closed without merging**
