### PR TITLE
fix(server) HEVC black screen on some linux config

### PR DESCRIPTION
**Pull request by Nibor62**
Fix for https://github.com/alvr-org/ALVR/issues/2202

After a bit of bisection, I found out that reverting this line fixed the blackscreen issue on my config.

WARN: even though I found that it fixes the issue I do not precisely understand why it does so.

### CODE REVIEW

**Comment by Nibor62** [comment]
So, from what I understand, the gop_frame is the frequency of intra_frame sending. I guess we have a very large number as it is not very usefull in the context of ALVR.
However it might be advised to ask @galister if reverting this modif is ok

**Comment by Vixea** [comment]
May I ask what distro?

**Comment by Nibor62** [comment]
I am on arch

**Comment by The-personified-devil** [comment]
Tbh I don't understand why it's that ridiculously high anyways

**Comment by Vixea** [comment]
Because we want to insert idrs/I frames when we want to not at the end of gop so higher sized gop means less "unexpected" idr/I frames

**Comment by The-personified-devil** [comment]
Ik, but int max is still ridiculous

**Comment by The-personified-devil** [comment]
Would this insert I frames or IDR frames? Because if it's I frames I see no issue with possibly wrongly inserting one every ~4 minutes at 120 fps

**Comment by Stormshield-robinc** [comment]
May  I ask if you have any news here ?

Newbie question : you that "I" frames were ok, so I guess that IDR are not. What is the different between the two and how do they impact with alvr ?

**Comment by Nibor62** [comment]
May I ask if you have any news here ?

Newbie question : you that "I" frames were ok, so I guess that IDR are not. What is the different between the two and how do they impact with alvr ?

**Comment by The-personified-devil** [comment]
I frames are frames that aren't encoded as differences to previous frames. IDR frames do this but also don't allow any frames before the I frame to be referenced. This will cause pixelated frames because without all the encoding tricks only a pixelated frame can satisfy the bitrate requirements for an IDR frame.

**Comment by zarik5** [comment]
I would add, the workaround should be documented with a comment explaining the reasons behind it.

**Comment by Nibor62** [comment]
updated

**Comment by zarik5** [comment]
Needs rebasing

**Review by Vixea — APPROVED** [review]

**Review by zarik5 — APPROVED** [review]

**Pull request merged**
