### PR TITLE
Vulkan: Fix Renderer/FrameConverter destructor crash when init fails

### PR DESCRIPTION
**Pull request by nowrep**
Make sure things don't crash when Renderer/FrameConverter init fails.
Also check for required extensions.

### CODE REVIEW

**Comment by Vixea** [comment]
LGMT! but while you at it could you check for style(open code and format it)

**Comment by nowrep** [comment]
What style?

**Comment by Vixea** [comment]
Good question: I don't know but zarik does. When asking me to do it he said launch code go to command palette and search format and run that.

**Comment by nowrep** [comment]
Do it in separate commit then. Don't add coding style changes next to normal code changes since that breaks `git blame`.
Also put the coding style commits to `.git-blame-ignore-revs`.

**Comment by Vixea** [comment]
eh I'll merge and just do one big format change.

**Review by Vixea — APPROVED** [review]

**Comment by zarik5** [comment]
If these files were never formatted, then don't bother formatting them now.

**Comment by Vixea** [comment]
Yeah, the weren't formatted

**Pull request merged**
