### PR TITLE
Flatpak: Install desktop file

### PR DESCRIPTION
**Pull request by Vixea**

### CODE REVIEW

**Comment by Vixea** [comment]
This is as tight as I could make it without a build failure.

**Review by Meister1593 — APPROVED** [review]

**Comment by Crafty-Codes** [comment]
Flatpak build stopped working for me because of [this line](https://github.com/alvr-org/ALVR/pull/1906/files#diff-a7d957170e40fecbe16cfaec0c539e68471c42265a75647cd0221d1eadacf968R50)

Error message:
Running: cp -r /run/build/alvr/build/alvr_streamer_linux/* /app/utils/alvr
Running: cp -r /run/build/alvr/alvr/xtask/flatpak/com.valvesoftware.Steam.Utility.alvr.desktop ~/.local/share/applications/com.valvesoftware.Steam.Utility.alvr.desktop
cp: cannot create regular file '/home/crafty/.local/share/applications/com.valvesoftware.Steam.Utility.alvr.desktop': No such file or directory
Error: module alvr: Child process exited with code 1

**Comment by Vixea** [comment]
What does your --filesystem argument equal?

**Comment by Crafty-Codes** [comment]
i only have a folder under ~/Games added

**Comment by Vixea** [comment]
Huh, I wasn't asking for that

**Comment by Crafty-Codes** [comment]
Ah sorry, i used it the first time with nothing and the second with --filesystem="$(pwd)"

**Comment by Vixea** [comment]
You don't need that unless installing it on a second drive

**Comment by Vixea** [comment]
Aka basically the only reason why you would have it cloned in at least a subdirectory or home

**Comment by Vixea** [comment]
Anyway what does the --filesystem say in the json file

**Comment by Crafty-Codes** [comment]
I use the newest git version of alvr so it has the added ["--filesystem=xdg-data"](https://github.com/alvr-org/ALVR/blob/master/alvr/xtask/flatpak/com.valvesoftware.Steam.Utility.alvr.json#L25C30-L25C30) line in it

**Pull request merged**
