### PR TITLE
Encode in full range color for NvEncoder on H264/HEVC

### PR DESCRIPTION
**Pull request by shinyquagsire23**
Very simple, 2 line fix, verified on visionOS client

### CODE REVIEW

**Review by zarik5 — APPROVED** [review]
Looks great!

**Comment by zarik5** [comment]
Tests showed that there is no easy way to make this work on android headsets (Quest, Pico etc). So we need at least a comment (in the setting name or help tooltip) saying that it only works on Nvidia + Apple Vision Pro.

**Comment by Vixea** [comment]
I disagree since we're just going to merge my pr soon after

**Comment by Vixea** [comment]
(just the nvidia part the Apple Vision Pro part is ok)

**Comment by zarik5** [comment]
@shinyquagsire23 the full range fix on the Android side needs to be applied conditionally

**Review by zarik5 — APPROVED** [review]

**Review by Vixea — APPROVED** [review]

**Pull request merged**
