### PR TITLE
Add fedora building guide and add dependencies to the wiki

### PR DESCRIPTION
**Pull request by Hsky17**
As tested by Grillo in the ALVR discord, this pull adds the needed dependencies to the wiki along with my guide for installing and using cuda on Fedora with ALVR. I think this would clear a lot of the confusion and make it easier for people using Fedora to build a working ALVR without having to figure out the dependencies and workarounds for Cuda. I have tested this on my machine and Grillo's machine and both work. If there are any problems let me know because this is my first pull request

Grillo's success with the guide

### CODE REVIEW

**Comment by zarik5** [comment]
I think the Fedora instructions should not be in a txt file. Either make another md file (with proper formatting) or better put the instructions in the Building form Source wiki page.

**Comment by Hsky17** [comment]
I can definitely make an md file for the guide that is a great idea. I dont think we should have it in the build instructions though because it would make it much longer for one specific issue. But also moving it to the bottom or something would work too. Ill work on converting it to a md file today

**Comment by zarik5** [comment]
> But also moving it to the bottom or something would work too

Moving it to the bottom as an addendum could be an idea. Just make sure things are as clear and clean as possible. technically you can make self-referencing links to just to the section inside the same md file, but I don't remember the syntax.

**Comment by zarik5** [comment]
You can use an internal ref for the link. something like `[text](#section-name)`

**Comment by Hsky17** [comment]
Yeah, I added internal references for accessing the guide and skipping to Client Building if you do need the guide. I just need to change the links again so it's for the ALVR GitHub and not my own. Let me know though if I should change anything, I can put the guide in a separate md file if needed.

**Comment by zarik5** [comment]
Not exactly what I meant, but also not sure I ever got it to work. Merging for now

**Pull request merged**
