### PR TITLE
feat(client): :sparkles: Expose server version from client_core

### PR DESCRIPTION
**Pull request by zarik5**
The new C API is `alvr_get_server_version` which works similarly to `alvr_get_settings_json`. The value can be obtained only after server connection, and the string length can be obtained by passing a null buffer.

### CODE REVIEW

**Comment by shinyquagsire23** [comment]
Tested it on visionOS and it seems to work fine, defaults to "20.11.0" on older versions but it seems like `client_core` works fine for those versions anyhow

**Review by shinyquagsire23 — APPROVED** [review]

**Comment by zarik5** [comment]
@shinyquagsire23  What do you mean "defaults to "20.11.0" on older versions"? What did you try?

**Review by The-personified-devil — APPROVED** [review]

**Comment by shinyquagsire23** [comment]
@zarik5 I tested streamer 20.9 and 20.10 from Releases with the patched client_core and it always returned the string "20.11.0"

**Comment by zarik5** [comment]
Now I remember why. This is actually caused by sloppy session extrapolation. Thankfully i can implement a fix and this will work retroactively for previous server builds.

**Comment by The-personified-devil** [comment]
> Thankfully i can implement a fix and this will work retroactively for previous server builds.

Do you mean knowing that the version is <= 20.11 is good enough and the fix in the server will be implemented later?

**Comment by zarik5** [comment]
No, i mean that the server version is already passed correctly but the client mistakenly overwrites and loses the value, because of faulty session extrapolation

**Comment by The-personified-devil** [comment]
that's what I was wondering, odd choice to not directly add the fix to the pr then

**Comment by zarik5** [comment]
I was thinking about that. You may be right. I'll make another PR tomorrow

**Comment by shinyquagsire23** [comment]
honestly for visionOS it kinda works out anyhow, because the issue I thought I needed the versions to patch over (controllers being rotated) was fixed with the client_core update anyhow. Though I might disable the hand skeleton hysteresis on older versions where SteamVR input 2.0 gets set true by default w/o the streamer having those settings present

**Pull request merged**
