### PR TITLE
Linux: use 1.1 frame VBV buffer size for all encoders

### PR DESCRIPTION
**Pull request by deiteris**

### CODE REVIEW

**Comment by galister** [comment]
tested this for ~20m and did not see anything weird

**Comment by galister** [comment]
never mind about the previous comment, I must have mixed something up

this actually won't build for me on linux:

```
alvr/server/cpp/platform/linux/EncodePipelineSW.cpp:90: undefined reference to `alvr::EncodePipelineSW::SetBitrate(long)'
```

**Comment by deiteris** [comment]
> never mind about the previous comment, I must have mixed something up
> 
> this actually won't build for me on linux:
> 
> ```
> alvr/server/cpp/platform/linux/EncodePipelineSW.cpp:90: undefined reference to `alvr::EncodePipelineSW::SetBitrate(long)'
> ```

Whoops, should be fixed now.

**Review by Vixea — APPROVED** [review]

**Comment by Vixea** [comment]
I believe this has been tested well enough and for long enough that it can be merged, now!

**Pull request merged**
