### PR TITLE
wip: replacing x264 with openh264

### PR DESCRIPTION
**Pull request by grillo-delmal**
I started this mostly to see how hard could it be, and even if I got to a point where it compiles (if you have the dependencies available),it crashes when forcing SWEncoding...

Mainly sharing it cos I'm short in time to deal with this and I'm curious to see if someone knows what's wrong with it, but I might continue with this later

### CODE REVIEW

**Comment by The-personified-devil** [comment]
What would the advantage of openh264 be over x264 tho?

**Comment by zarik5** [comment]
I think i'd close this just because openh264 has much worse performance than x264. Openh264 is MIT which is better but most definitely unusable, given that x264 has barely the minimum performance required for VR.

**Comment by grillo-delmal** [comment]
> What would the advantage of openh264 be over x264 tho?

**Comment by grillo-delmal** [comment]
> What would the advantage of openh264 be over x264 tho?

I doubt there would be any other than making the app easier to distribute. 

> I think i'd close this just because openh264 has much worse performance than x264. Openh264 is MIT which is better but most definitely unusable, given that x264 has barely the minimum performance required for VR.

I've heard this argument too, and tbh, I agree, but at the very least i'd like to see it for myself :)

**Comment by zarik5** [comment]
> I doubt there would be any other than making the app easier to distribute.

It's true. But right now given the very poor performance of software encoding, it's is just a gimmick for users to try out, and these users don't really care about licensing.

**Comment by zarik5** [comment]
Given that the target audience is laptop users, i doubt that

**Pull request closed without merging**
