### PR TITLE
Linux: Remove AMF encoder

### PR DESCRIPTION
**Pull request by nowrep**
With all the recent Mesa changes there is no point using AMF instead of VAAPI anymore.

### CODE REVIEW

**Comment by nowrep** [comment]
The original motivation was that VAAPI was slower and had latency spikes which is now fixed. There are also new features like intra-refresh, full-range, ... which ALVR doesn't use now but may in the future.

Currently there is no feature that AMF has but VAAPI lacks that would be useful for ALVR.

**Comment by zarik5** [comment]
LGTM. to be hones I think almost noone was using AMF on linux because that had to be enabled using environment variables which was unintuitive and obscure. But correct me if i'm wrong.

**Comment by andy-d1969** [comment]
I'm using AMF on Linux, and it works still better here than VAAPI. With VAAPI I get short freezes on high GPU load and the latency with AMF is a little lower.

**Comment by nowrep** [comment]
@andy-d1969 You can try this Mesa patch and see if that helps:

<details>
  <summary>vcn-latency.diff</summary>

```diff
diff --git a/src/gallium/drivers/radeonsi/radeon_vcn_enc_1_2.c b/src/gallium/drivers/radeonsi/radeon_vcn_enc_1_2.c
index 6167c9575ab..35e9af75fb9 100644
--- a/src/gallium/drivers/radeonsi/radeon_vcn_enc_1_2.c
+++ b/src/gallium/drivers/radeonsi/radeon_vcn_enc_1_2.c
@@ -178,6 +178,11 @@ static void radeon_enc_rc_session_init(struct radeon_encoder *enc)
    RADEON_ENC_CS(enc->enc_pic.rc_session_init.rate_control_method);
    RADEON_ENC_CS(enc->enc_pic.rc_session_init.vbv_buffer_level);
    RADEON_ENC_END();
+
+   /* low latency mode ? */
+   RADEON_ENC_BEGIN(24);
+   RADEON_ENC_CS(1000);
+   RADEON_ENC_END();
 }
 
 static void radeon_enc_rc_layer_init(struct radeon_encoder *enc)
```

</details>

**Comment by andy-d1969** [comment]
With the Mesa patch the latency is now identical with AMF.

**Comment by Vixea** [comment]
Merging then

**Comment by Vixea** [comment]
I'm actually thinking about reverting this now that the foss drivers work with amf and there're still weird latency issues unresolved

**Pull request merged**
