### PR TITLE
finalize-dashboard: add some more strings

### PR DESCRIPTION
**Pull request by galister**

### CODE REVIEW

**Comment by zarik5** [comment]
Thanks!

**Comment by zarik5** [comment]
why did you close this? I didn't merge it yet to avoid more merge conflicts while rebasing the finalize-dashboard branch

**Comment by galister** [comment]
thought it'd be easier to just redo, one the main dashboard pr is closer to merging.

**Comment by zarik5** [comment]
These changes have been included in #1446. Closing

**Pull request closed without merging**
