### PR TITLE
Brute-Force OpenVR-FSR support.

### PR DESCRIPTION
**Pull request by toomuchcodehelp**
literally followed the instructions from the [repo](https://github.com/fholger/openvr_fsr). All the checks passed on my fork, but i would like if someone on windows would check it for themselves. This partially solves #1238.

### CODE REVIEW

**Comment by Vixea** [comment]
I don't really like this solution its better to wait till we have are own compositor as I'm pretty sure vrc does not like this(easy-anticheat)

**Comment by toomuchcodehelp** [comment]
i agree that this is a little primitive, but it does implement FSR

**Comment by KlowNJ420** [comment]
How do I enable FSR from using this? I've built it on windows and it runs, but it does not look upscaled....

**Comment by toomuchcodehelp** [comment]
manually edit the .cfg file

**Comment by toomuchcodehelp** [comment]
files here: https://github.com/alvr-org/ALVR/pull/1245/commits/dbf0918791509b647b1eac8471342157c9614a4e

**Comment by KlowNJ420** [comment]
I've checked the config, and I've enable the debug mode inside the config file. Upscaling is not happening nor does debug mode appear inside the HMD. It is not working on Windows. Am I failing to enable something?

**Comment by toomuchcodehelp** [comment]
i believe that there is a far better solution to all of this, that runs on the client and therefore supports linux. I'm closing this for now.

**Pull request closed without merging**
