### PR TITLE
fix(ci): 🐛 Enable GPL on linux build and remove AppImage from CI

### PR DESCRIPTION
**Pull request by Meister1593**
Same deal as on nightlies

### Merge only after it gets tested at least on nightlies, otherwise i don't know if it works on nvidia (double-checking removal of nc-codec-headers)

### CODE REVIEW

**Comment by Meister1593** [comment]
...theres literally no code change, and it ran just fine before i change commit name

ignore macos check?...
image

**Comment by zarik5** [comment]
Yeah it likes to fail on alvr_packets for some reason

**Review by zarik5 — APPROVED** [review]

**Comment by MadByteDE** [comment]
Sry for asking but why removing AppImages? They worked just fine for me on nvidia.

**Comment by PassiveLemon** [comment]
I'm interested in why as well.

**Comment by Meister1593** [comment]
AppImages weren't required anymore (almost everything is bundled into alvr as static library now, appimage reason for being portable is nulled at this point) and it was maintenance burden that no one knew how to properly maintain, thus it was removed as unnecessary.

**Comment by guysoft** [comment]
Hey, so I am trying to run the linux build and its crashing. I am not sure why, but this did not happen with the appimage. Is there a way to figure what is missing in the native build?

**Comment by Meister1593** [comment]
@guysoft please open new issue and provide output of `ldd bin/alvr_dashboard` and `lib64/alvr/bin/linux64/driver_alvr_server.so` with it

**Comment by mAd-DaWg** [comment]
@Meister1593 for the same reason please remove flatpack, as the exact same logic applies

**Comment by Meister1593** [comment]
Flatpak is made fairly differently but removing flatpak build is planned as well. Just need to update instructions how to use with tar instead of it. It might be also possible to use it with nvidia that way.

**Comment by guysoft** [comment]
Updating that my issue was fixed. I am now using the static build which works for me.

**Pull request merged**
