### PR TITLE
AMF: move library and rename the windows encoder

### PR DESCRIPTION
**Pull request by Vixea**
another nice refactor I though of while just chilling

### CODE REVIEW

**Comment by Vixea** [comment]
macos action seems to be down rn

**Comment by zarik5** [comment]
> macos action seems to be down rn
It's your changes. The shared folder is included in the macos build but now you added the incompatible AMF headers.

**Comment by Vixea** [comment]
ah, makes sense

**Review by zarik5 — APPROVED** [review]
If noone has objections, this can be merged.

**Pull request merged**
