### PR TITLE
fix: linux views when using modified playspace

### PR DESCRIPTION
**Pull request by galister**
Closes https://github.com/alvr-org/ALVR/issues/2013

What was changed:
- mat3x3 multiplication in `OnPoseUpdated` was wrong
  - replaced with `vrmath::matMul33`
  - this alone fixed playspace rotation but only while using standing universe
- do not throw away queued poses when playspace changes
  - with the old logic, there would be ~1s drunken period
  - transition is smooth after the change
- switch to `VRApplication_Background`
  -  this is to get access to `GetTrackingSpace()` which tells us if the universe is seated or standing
- pull seated or standing transform based on current universe
- handle more events that can cause the playspace to shift
  - previously, it would only trigger on universe change (standing <> seated)
- `InitOpenvrClient` and `ShutdownOpenvrClient` are now state-aware
- An automatic recovery mechanism was added that triggers if the reported game_render time goes above 250ms.

Thanks to @Vixea for gathering info & testing

### CODE REVIEW

**Comment by galister** [comment]
Another thing we could add as a safety net is to force a `poseHistory->SetTransform(GetRawZeroPose());` when there have been too many consecutive pose history misses, but I haven't run into a case that the current solution didnt't handle.

**Comment by Meister1593** [comment]
does this fix issue with slimevr, some games like space engine, recenter in steamvr changing playerspace and breaking view completely?

**Comment by galister** [comment]
the game i tested was subnautica + vr mod, which had a bad case of triggering the issue on the title screen even. recenter and playspace rotate are also fixed. i would think slimevr as well, though i only tested with vive trackers. feel free to test and let me know.

**Comment by galister** [comment]
note that wlx-s will also need to be updated to support rotated playspaces for space drag, you may get weird results with it as of now

**Review by zarik5 — APPROVED** [review]
No concerns style-wise. I haven't tested myself

**Review by Meister1593 — APPROVED** [review]

**Pull request merged**
