### PR TITLE
YVR1/2 support

### PR DESCRIPTION
**Pull request by muxiaozi**

### CODE REVIEW

**Comment by zarik5** [comment]
Thank you! This looks very amazing! The windows and linux failures are unrelated, let me fix them first.

**Comment by muxiaozi** [comment]
This project is very good, thank you for your positive contribution. And this HMD is designed by PLAY FOR DREAM (https://yvrdream.com/)

**Comment by zarik5** [comment]
Keep in mind that in future versions we may introduce bugs we can't test because we don't own the hardware. You are welcome to submit patches if you see any compatibility issues.

**Comment by muxiaozi** [comment]
No problem

**Comment by zarik5** [comment]
Please force push again to rerun the CI checks

**Pull request merged**
