### PR TITLE
V20 staging

### PR DESCRIPTION
**Pull request by zarik5**
This is a intermediate PR with the purpose of Applab release. Actual v20.9.0 should be released after PipeWire support is merged.

This is a merge of the latest master commits except 110479fbf202d94419cbf4c62329617fda8efa47 .

### CODE REVIEW

**Comment by The-personified-devil** [comment]
Why not include the USB fix, it doesn't break anything?

**Review by The-personified-devil — APPROVED** [review]

**Comment by zarik5** [comment]
@The-personified-devil the usb fix is based on code that also was not included in v20 (mdns) because it;s a breaking change. the previous master code and v20 do not have broken usb to begin with.

**Comment by The-personified-devil** [comment]
duh, not rlly thinking today

**Comment by zarik5** [comment]
Everything alright, was not clarified :)

**Pull request merged**
