### PR TITLE
Zarik staging

### PR DESCRIPTION
**Pull request by zarik5**
Undoing the dependencies bump because egui is bugged. Also downgrading wgpu because of another reported crash.

### CODE REVIEW

**Review by The-personified-devil — APPROVED** [review]
Don't really like downgrading wgpu. Whats the crash exactly?

**Comment by zarik5** [comment]
Possibly #2446 but i cannot reproduce and i don't have any evidence that downgrading fixes the issue. In any case i remember having issues upgrading only wgpu because egui 0.28 would complain

**Comment by The-personified-devil** [comment]
If it's tied to egui, then sure, it's fine

**Comment by The-personified-devil** [comment]
Tbh we could've only downgraded wgpu for the dash and not for the client, but doesn't really matter

**Comment by zarik5** [comment]
Apparently it's not a good idea. wgpu often relies on pinning versions of web-sys, and if it's not that, some other dependencies make it impossible to build two versions together. This is actually the reason why egui should be updated in lockstep with wgpu

**Pull request merged**
