### PR TITLE
Pico4 support

### PR DESCRIPTION
**Pull request by galister**

### CODE REVIEW

**Comment by zarik5** [comment]
Great! All good :)

**Comment by korejan** [comment]
@galister I don't mind copying code but at at least acknowledge the source and that you didn't make this fix. This fix is obviously been replicated from my recent commit to ALXR because i pushed it a few hours earlier than this MR.

**Comment by galister** [comment]
I can assure you that this PR does not contain any code copied from, or inspired by ALXR.

**Comment by Vixea** [comment]
Can I please see the the commit that introduced the code that is being claimed copied in this pr, as i can't find in in any of your commits please excuse my inability to find it as it's rather late for me?

**Comment by galister** [comment]
Also, the controller knowledge is taken from the official Pico Unity OpenXR plugin.

**Comment by zarik5** [comment]
Also i can assure i'm not even looking at ALXR for developing OpenXR in ALVR.

**Comment by Vixea** [comment]
> Also, the controller knowledge is taken from the official Pico Unity OpenXR plugin.

Oh seems reasonable enough mind sending the docs for that

**Comment by galister** [comment]
> > Also, the controller knowledge is taken from the official Pico Unity OpenXR plugin.
> 
> Oh seems reasonable enough mind sending the docs for that

Download:
https://developer-global.pico-interactive.com/sdk?deviceId=1&platformId=1&itemId=7153484514247917573

See: `./Runtime/Interactions/PICOTouchControllerProfile.cs`

**Comment by lman0** [comment]
Also, the controller knowledge is taken from the official Pico Unity OpenXR plugin.

Oh seems reasonable enough mind sending the docs for that

Download:
https://developer-global.pico-interactive.com/sdk?deviceId=1&platformId=1&itemId=7153484514247917573

See: ./Runtime/Interactions/PICOTouchControllerProfile.cs

@galister  @zarik5  is the PR content is copied  , or copied and renamed) from this file?

If yes , then the PR  must be reverted , this it's basically stealing a code from another license...

And the pico license forbid to copy a code that could be reused for  third parties .

Even if the source is 'open' , it don't mean you could do license infringement, by copy pasting part of the code...

Pico could very well close alvr, thank to this PR if this the case.

**Comment by lman0** [comment]
Please remember someone sued Microsoft because copilot copied gpl3 licensed code to another kind of  licensed project .
Pico could do the same , and make github close this repo altogether...

**Comment by zarik5** [comment]
We are not using any sample code, only the SDK. in any case it would be stupid to license SDK resources as anything other than open + commercial license. If you are worried about it, you can open a ticket in the Pico forum.

**Comment by lman0** [comment]
@zarik5  it's worse if it's the SDK code , that you copied , because it's the property of pico and covered explicitly by the license. (Please read it before download!).
And the open license can very well be incompatible with alvr license .
With specific close that make the code illegal if used for occulus, or other third parties.

**Comment by lman0** [comment]
@zarik5  if I send a ticket to pico, and what I think is true then alvr will be closed on spot....

**Comment by zarik5** [comment]
No worries in this regard, trust me :) But go ahead and open the ticket.

**Comment by lman0** [comment]
Where is the link for this ?
I don't own a pico

**Comment by galister** [comment]
Rest assured the code was not copied from the Pico Unity Plugin. That plugin is in C# and we work in Rust.

It was simply used to verify what capabilities and config values the controllers need in order to work. This was necessary because Pico does not document these anywhere else.

**Comment by galister** [comment]
However please feel free to check the file at the path I mentioned from the Pico OpenXR Unity Plugin and compare it to our controller code in this PR and let us know what you think.

**Comment by lman0** [comment]
@galister thanks for explaining!
I ve seen project be closed by license infringement so I was afraid for alvr.
Since it about value and not code, then it should be not a problem like you said @galister @zarik5 .

**Pull request merged**
